name: walkingpet
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedometer: ^4.0.1
  permission_handler: ^11.3.1
  vibration: ^1.8.4
  flutter_blue_plus: ^1.32.4
  flutter_foreground_task: ^6.1.3
  cupertino_icons: ^1.0.6
  pixelarticons: ^0.4.0
  flutter_svg: ^2.0.1
  nes_ui: ^0.20.0
  provider: ^6.1.2
  motion_tab_bar: ^2.0.4
  http: ^1.2.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: DungGeunMo
      fonts:
        - asset: assets/fonts/DungGeunMo.ttf

  assets:
    - assets/
    - assets/animals/
    - assets/animals/cow/
    - assets/animals/dragons/red/
    - assets/backgrounds/
    - assets/buttons/
    - assets/icons/
    - assets/images/
    - assets/items/
